In [21]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [22]:
filepath="kc_house_data.csv"
house_data=pd.read_csv(filepath)

In [23]:
house_data.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [24]:
house_data.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [25]:
#sns.pairplot(house_data)

In [26]:
#sns.scatterplot(x='sqft_living',y='price',data=house_data)

In [27]:
X=house_data.drop(['price','id','date','long','view','waterfront'],axis=1)
y=house_data['price']

In [28]:
X.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,sqft_living15,sqft_lot15
0,3,1.00,1180,5650,1.0,3,7,1180,0,1955,0,98178,47.5112,1340,5650
1,3,2.25,2570,7242,2.0,3,7,2170,400,1951,1991,98125,47.7210,1690,7639
2,2,1.00,770,10000,1.0,3,6,770,0,1933,0,98028,47.7379,2720,8062
3,4,3.00,1960,5000,1.0,5,7,1050,910,1965,0,98136,47.5208,1360,5000
4,3,2.00,1680,8080,1.0,3,8,1680,0,1987,0,98074,47.6168,1800,7503

In [29]:
from sklearn.feature_selection import SelectKBest, chi2,f_regression

In [30]:
selector=SelectKBest(chi2,k=14)
selector.fit_transform(X,y)
selector.get_support()

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True])

In [31]:
X=X[np.array(X.columns[selector.get_support()])]

In [32]:
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import SGDClassifier,Ridge,Lasso
from sklearn.preprocessing import StandardScaler,PolynomialFeatures,RobustScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error
from sklearn.svm import SVC,LinearSVC

In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0)

In [40]:
model=make_pipeline(SimpleImputer(strategy='median'),RobustScaler(),Lasso(alpha=10,max_iter=100000))
#model=make_pipeline(SimpleImputer(),StandardScaler(),Lasso(alpha=0.2,max_iter=10000))
#model=Ridge(alpha=0.01)

In [41]:
model.fit(X_train,y_train)

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('robustscaler', RobustScaler()),
                ('lasso', Lasso(alpha=10, max_iter=100000))])

In [42]:
model.score(X_test,y_test)

0.6189551668646447

In [37]:
from sklearn.model_selection import learning_curve

In [38]:
# N,train_score,val_score=learning_curve(model,X_train,y_train,train_sizes=np.linspace(0.1,1.0,50),cv=4)
# print(N)
# plt.plot(N,train_score.mean(axis=1),label='train')
# plt.plot(N,val_score.mean(axis=1),label='validation')
# plt.xlabel('train sizes')
# plt.legend()
# plt.show()

In [45]:
params={'fit_intercept':['True','False'],'alpha':[0.8,1,2,3,4,5],'selection':['cyclic', 'random'],'max_iter':[1000,5000,10000,100000]}
grid=GridSearchCV(model,param_grid=params, cv=4)

grid.fit(X_train,y_train)

ValueError: Invalid parameter alpha for estimator Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('robustscaler', RobustScaler()),
                ('lasso', Lasso(alpha=10, max_iter=100000))]). Check the list of available parameters with `estimator.get_params().keys()`.

In [46]:
grid.best_estimator_

AttributeError: 'GridSearchCV' object has no attribute 'best_estimator_'

In [55]:
grid.best_score_

0.5698432391179601